export const COUNTRY_CODES: Record<string, string> = {
  "AF": "Afghanistan",
  "AL": "Albania",
  "DZ": "Algeria",
  "AS": "American Samoa",
  "AD": "Andorra, Principality of",
  "AO": "Angola",
  "AI": "Anguilla",
  "AQ": "Antarctica",
  "AG": "Antigua and Barbuda",
  "AR": "Argentina",
  "AM": "Armenia",
  "AW": "Aruba",
  "AU": "Australia",
  "AT": "Austria",
  "AZ": "Azerbaijan or Azerbaidjan",
  "BS": "Bahamas, Commonwealth of The",
  "BH": "Bahrain, Kingdom of",
  "BD": "Bangladesh",
  "BB": "Barbados",
  "BY": "Belarus",
  "BE": "Belgium",
  "BZ": "Belize",
  "BJ": "Benin",
  "BM": "Bermuda",
  "BT": "Bhutan, Kingdom of",
  "BO": "Bolivia",
  "BA": "Bosnia and Herzegovina",
  "BW": "Botswana",
  "BV": "Bouvet Island",
  "BR": "Brazil",
  "IO": "British Indian Ocean Territory",
  "BN": "Brunei",
  "BG": "Bulgaria",
  "BF": "Burkina Faso",
  "BI": "Burundi",
  "KH": "Cambodia, Kingdom of",
  "CM": "Cameroon",
  "CA": "Canada",
  "CV": "Cape Verde",
  "KY": "Cayman Islands",
  "CF": "Central African Republic",
  "TD": "Chad",
  "CL": "Chile",
  "CN": "China",
  "CX": "Christmas Island",
  "CC": "Cocos (Keeling) Islands",
  "CO": "Colombia",
  "KM": "Comoros, Union of the",
  "CD": "Congo, Democratic Republic of the",
  "CG": "Congo, Republic of the",
  "CK": "Cook Islands",
  "CR": "Costa Rica",
  "CI": "Cote D'Ivoire",
  "HR": "Croatia",
  "CU": "Cuba",
  "CY": "Cyprus",
  "CZ": "Czech Republic",
  "CS": "Czechoslavakia",
  "DK": "Denmark",
  "DJ": "Djibouti",
  "DM": "Dominica",
  "DO": "Dominican Republic",
  "TP": "East Timor",
  "EC": "Ecurador",
  "EG": "Egypt",
  "SV": "El Salvador",
  "GQ": "Equatorial Guinea",
  "ER": "Eritrea",
  "EE": "Estonia",
  "ET": "Ethiopia",
  "FK": "Falkland Islands",
  "FO": "Faroe Islands",
  "FJ": "Fiji",
  "FI": "Finland",
  "FR": "France",
  "GF": "French Guiana or French Guyana",
  "PF": "French Polynesia",
  "TF": "French Southern Territories and Antarctic Lands",
  "GA": "Gabon",
  "GM": "Gambia, The",
  "GE": "Georgia",
  "DE": "Germany",
  "GH": "Ghana",
  "GI": "Gibraltar",
  "GB": "Great Britain",
  "GR": "Greece",
  "GL": "Greenland",
  "GD": "Grenada",
  "GP": "Guadeloupe",
  "GU": "Guam",
  "GT": "Guatemala",
  "GN": "Guinea",
  "GW": "Guinea-Bissau",
  "GY": "Guyana",
  "HT": "Haiti",
  "HM": "Heard Island and McDonald Islands",
  "VA": "Holy See",
  "HN": "Honduras",
  "HK": "Hong Kong",
  "HU": "Hungary",
  "IS": "Iceland",
  "IN": "India",
  "ID": "Indonesia",
  "IR": "Iran, Islamic Republic of",
  "IQ": "Iraq",
  "IE": "Ireland",
  "IL": "Israel",
  "IT": "Italy",
  "JM": "Jamaica",
  "JP": "Japan",
  "JO": "Jordan",
  "KZ": "Kazakstan or Kazakhstan",
  "KE": "Kenya",
  "KI": "Kiribati",
  "KP": "Korea, Democratic People's Republic of",
  "KR": "Korea, Republic of",
  "KW": "Kuwait",
  "KG": "Kyrgyzstan",
  "LA": "Lao People's Democratic Republic",
  "LV": "Latvia",
  "LB": "Lebanon",
  "LS": "Lesotho",
  "LR": "Liberia",
  "LY": "Libya",
  "LI": "Liechtenstein",
  "LT": "Lithuania",
  "LU": "Luxembourg",
  "MO": "Macau",
  "MK": "Macedonia, The Former Yugoslav Republic of",
  "MG": "Madagascar",
  "MW": "Malawi",
  "MY": "Malaysia",
  "MV": "Maldives",
  "ML": "Mali",
  "MT": "Malta",
  "MH": "Marshall Islands",
  "MQ": "Martinique",
  "MR": "Mauritania",
  "MU": "Mauritius",
  "YT": "Mayotte",
  "MX": "Mexico",
  "FM": "Micronesia, Federated States of",
  "MD": "Moldova, Republic of",
  "MC": "Monaco, Principality of",
  "MN": "Mongolia",
  "MS": "Montserrat",
  "MA": "Morocco",
  "MZ": "Mozambique",
  "MM": "Myanmar, Union of",
  "NA": "Namibia",
  "NR": "Nauru",
  "NP": "Nepal",
  "NL": "Netherlands",
  "AN": "Netherlands Antilles",
  "NC": "New Caledonia",
  "NZ": "New Zealand",
  "NI": "Nicaragua",
  "NE": "Niger",
  "NG": "Nigeria",
  "NU": "Niue",
  "NF": "Norfolk Island",
  "MP": "Northern Mariana Islands",
  "NO": "Norway",
  "OM": "Oman, Sultanate of",
  "PK": "Pakistan",
  "PW": "Palau",
  "PS": "Palestinian State",
  "PA": "Panama",
  "PG": "Papua New Guinea",
  "PY": "Paraguay",
  "PE": "Peru",
  "PH": "Philippines",
  "PN": "Pitcairn Island",
  "PL": "Poland",
  "PT": "Portugal",
  "PR": "Puerto Rico",
  "QA": "Qatar, State of",
  "RE": "Reunion",
  "RO": "Romania",
  "SU": "Russia - USSR",
  "RU": "Russian Federation",
  "RW": "Rwanda",
  "SH": "Saint Helena",
  "KN": "Saint Kitts and Nevis",
  "LC": "Saint Lucia",
  "PM": "Saint Pierre and Miquelon",
  "VC": "Saint Vincent and the Grenadines",
  "WS": "Samoa",
  "SM": "San Marino",
  "ST": "Sao Tome and Principe",
  "SA": "Saudi Arabia",
  "RS": "Serbia, Republic of",
  "SN": "Senegal",
  "SC": "Seychelles",
  "SL": "Sierra Leone",
  "SG": "Singapore",
  "SK": "Slovakia",
  "SI": "Slovenia",
  "SB": "Solomon Islands",
  "SO": "Somalia",
  "ZA": "South Africa",
  "GS": "South Georgia and the South Sandwich Islands",
  "ES": "Spain",
  "LK": "Sri Lanka",
  "SD": "Sudan",
  "SR": "Suriname",
  "SJ": "Svalbard and Jan Mayen Islands",
  "SZ": "Swaziland, Kingdom of",
  "SE": "Sweden",
  "CH": "Switzerland",
  "SY": "Syria",
  "TW": "Taiwan",
  "TJ": "Tajikistan",
  "TZ": "Tanzania, United Republic of",
  "TH": "Thailand",
  "TG": "Togo",
  "TK": "Tokelau",
  "TO": "Tonga, Kingdom of",
  "TT": "Trinidad and Tobago",
  "TE": "Tromelin Island",
  "TN": "Tunisia",
  "TR": "Turkey",
  "TM": "Turkmenistan",
  "TC": "Turks and Caicos Islands",
  "TV": "Tuvalu",
  "UG": "Uganda, Republic of",
  "UA": "Ukraine",
  "AE": "United Arab Emirates",
  "US": "United States",
  "UM": "United States Minor Outlying Islands",
  "UY": "Uruguay, Oriental Republic of",
  "UZ": "Uzbekistan",
  "VU": "Vanuatu",
  "VE": "Venezuela",
  "VN": "Vietnam",
  "VI": "Virgin Islands, British",
  "VQ": "Virgin Islands, United States",
  "WF": "Wallis and Futuna Islands",
  "EH": "Western Sahara",
  "YE": "Yemen",
  "YU": "Yugoslavia",
  "ZR": "Zaire",
  "ZM": "Zambia, Republic of",
  "ZW": "Zimbabwe, Republic of"
};

export interface ExportShipment {
  Shipper_Name: string;
  HS_Code: string;
  Declared_Description: string;
  Origin: string;
  Quantity: number | string;
  Unit_Value: number | string;
  Total_Value: number | string;
  IMO_Class: string;
  HAWB_Number: string;
  Parcel_Category: string;
  Sample_Category: string;
  Item_Export_Type: string;
  Gross_Weight: number | string;
  Unit_Weight_Code: string;
  Identity_Type: string;
  Identity_Number: string;
  Exporter_Name: string;
  Exporter_Address: string;
  Consignee_Name: string;
  Consignee_Address: string;
  Consignee_Country: string;
  Consignee_Country_Sub_Division: string;
  Consignee_City: string;
  Consignee_Street_PO_BOX: string;
  Consignee_Postal_Code: string;
  Repair_Replacement_ReturnFaulty_RejectedGoods: string;
  Remarks: string;
  GD_NO_Complete: string;
}

export interface Shipment {
  trackingNumber: string;
  shipperCompany: string;
  originLocCode: string;
  recipientName: string;
  destCity: string;
  pieceCount: number;
  weight: number;
  weightUOM: string;
  commodityDesc: string;
  customsValue: number;
  currencyCode: string;
  recipientPhone: string;
  originCountry: string;
  destCountry: string;
  postalCode: string;
}

export const INITIAL_SHIPMENTS: Shipment[] = [
  {
    trackingNumber: "870979541353",
    shipperCompany: "CLOTHOO NTN # 4214470-1",
    originLocCode: "SKTA",
    recipientName: "JARED MILLER",
    destCity: "LIBERTYVILLE",
    pieceCount: 1,
    weight: 1.0,
    weightUOM: "K",
    commodityDesc: "PKCLOSIA/6203.39.90.00 UNISEX JACKET M/O POLY COTT",
    customsValue: 40.0,
    currencyCode: "USD",
    recipientPhone: "6193129085",
    originCountry: "PK",
    destCountry: "US",
    postalCode: "60088"
  },
  {
    trackingNumber: "870979822816",
    shipperCompany: "CLOTHOO NTN # 4214470-1",
    originLocCode: "SKTA",
    recipientName: "SANDORA ANDERS",
    destCity: "SOUTH HOLLAND",
    pieceCount: 1,
    weight: 1.0,
    weightUOM: "K",
    commodityDesc: "PKCLOSIA/6103.31.00.00 UNISEX JACKET M/O MELTON W",
    customsValue: 50.0,
    currencyCode: "USD",
    recipientPhone: "7089064749",
    originCountry: "PK",
    destCountry: "US",
    postalCode: "60438"
  },
  {
    trackingNumber: "870979350889",
    shipperCompany: "CLOTHOO NTN # 4214470-1",
    originLocCode: "SKTA",
    recipientName: "MAC STEVENS",
    destCity: "ANCHORAGE",
    pieceCount: 1,
    weight: 1.0,
    weightUOM: "K",
    commodityDesc: "PKCLOSIA/6101.30.10.00 UNISEX JACKET M/O SATIN B",
    customsValue: 80.0,
    currencyCode: "USD",
    recipientPhone: "9078414074",
    originCountry: "PK",
    destCountry: "US",
    postalCode: "99502"
  },
  {
    trackingNumber: "870979419690",
    shipperCompany: "CLOTHOO NTN # 4214470-1",
    originLocCode: "SKTA",
    recipientName: "JONATHAN TEXEIRA",
    destCity: "SUNNYVALE",
    pieceCount: 1,
    weight: 1.0,
    weightUOM: "K",
    commodityDesc: "PKCLOSIA/6101.30.10.00 UNISEX JACKET M/O SATIN B",
    customsValue: 40.0,
    currencyCode: "USD",
    recipientPhone: "16692859176",
    originCountry: "PK",
    destCountry: "US",
    postalCode: "95051"
  },
  {
    trackingNumber: "870979628418",
    shipperCompany: "CLOTHOO NTN # 4214470-1",
    originLocCode: "SKTA",
    recipientName: "GABRIEL PELAYO",
    destCity: "LAWTON",
    pieceCount: 1,
    weight: 1.0,
    weightUOM: "K",
    commodityDesc: "PKCLOSIA/6103.31.00.00 UNISEX JACKET M/O MELTON W",
    customsValue: 50.0,
    currencyCode: "USD",
    recipientPhone: "9183819432",
    originCountry: "PK",
    destCountry: "US",
    postalCode: "73541"
  },
  {
    trackingNumber: "870979712823",
    shipperCompany: "CLOTHOO NTN # 4214470-1",
    originLocCode: "SKTA",
    recipientName: "LARISSA EVANS",
    destCity: "CALGARY",
    pieceCount: 1,
    weight: 4.0,
    weightUOM: "K",
    commodityDesc: "PKCLOSIA / 6103.31.00.00 UNISEX JACKET(S) M/O WOOL",
    customsValue: 80.0,
    currencyCode: "USD",
    recipientPhone: "4034738974",
    originCountry: "PK",
    destCountry: "CA",
    postalCode: "T2N2G6"
  },
  {
    trackingNumber: "870979771476",
    shipperCompany: "CLOTHOO NTN # 4214470-1",
    originLocCode: "SKTA",
    recipientName: "LIZ SMITH",
    destCity: "SAN BERNARDINO",
    pieceCount: 1,
    weight: 1.0,
    weightUOM: "K",
    commodityDesc: "PKCLOSIA/6101.30.10.00 UNISEX JACKET M/O SATIN B",
    customsValue: 50.0,
    currencyCode: "USD",
    recipientPhone: "9099159377",
    originCountry: "PK",
    destCountry: "US",
    postalCode: "92415"
  },
  {
    trackingNumber: "870979471846",
    shipperCompany: "CLOTHOO NTN # 4214470-1",
    originLocCode: "SKTA",
    recipientName: "MARK MENDAROS",
    destCity: "BROOKLYN",
    pieceCount: 1,
    weight: 1.0,
    weightUOM: "K",
    commodityDesc: "PKCLOSIA / 6103.31.00.00 UNISEX JACKET(S) M/O WOOL",
    customsValue: 186.0,
    currencyCode: "USD",
    recipientPhone: "4085332220",
    originCountry: "PK",
    destCountry: "US",
    postalCode: "11201"
  }
];
